### ISSUE TITLE
Bug: Clicking 'Connect' quickly (while already-open fort data is loading) causes seg fault

### ISSUE THREAD

**Issue by TylerPeterson085** [Dwarf-Therapist/Dwarf-Therapist#202]
If I have a fort open, then start Dwarf Therapist, if I click the "Connect" button while it is automatically loading the data, it results in a seg fault. The colors of the columns of the labors flash onto the window shortly before the program crashes.

I'm on Ubuntu 18.04.
Dwarf Therapist is 41.1.2.
Dwarf Fortress is 0.44.12

**Comment by cvuchener** [comment]
It's annoying I cannot reproduce it with a debug build (I can't click).

All I know is that it's related to the updater. You won't be able to click if the updates are disabled.

```
#0  0x0000558bfb82ef37 in DFInstance::find_memory_layout(QString) ()
#1  0x0000558bfba2b743 in Updater::find_layout_urls(QNetworkReply*) ()
#2  0x0000558bfba2d7c3 in Updater::check_layouts(DFInstance*) ()
#3  0x0000558bfb940375 in MainWindow::connect_to_df() ()
#4  0x0000558bfb7f4e85 in MainWindow::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) ()
#5  0x00007f86b119379a in QObject::event(QEvent*) () at /lib64/libQt5Core.so.5
#6  0x00007f86b21c2c28 in QWidget::event(QEvent*) () at /lib64/libQt5Widgets.so.5
#7  0x00007f86b22d9838 in QMainWindow::event(QEvent*) () at /lib64/libQt5Widgets.so.5
#8  0x00007f86b217fab6 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib64/libQt5Widgets.so.5
#9  0x00007f86b2189150 in QApplication::notify(QObject*, QEvent*) () at /lib64/libQt5Widgets.so.5
#10 0x00007f86b11683e8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib64/libQt5Core.so.5
#11 0x00007f86b116b42b in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
    at /lib64/libQt5Core.so.5
#12 0x00007f86b11bda97 in postEventSourceDispatch(_GSource*, int (*)(void*), void*) () at /lib64/libQt5Core.so.5
#13 0x00007f86afd90520 in g_main_context_dispatch () at /lib64/libglib-2.0.so.0
#14 0x00007f86afd908b0 in g_main_context_iterate.isra () at /lib64/libglib-2.0.so.0
#15 0x00007f86afd90953 in g_main_context_iteration () at /lib64/libglib-2.0.so.0
#16 0x00007f86b11bd825 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /lib64/libQt5Core.so.5
#17 0x00007f86b11671db in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt5Core.so.5
#18 0x00007f86b116f0b6 in QCoreApplication::exec() () at /lib64/libQt5Core.so.5
#19 0x0000558bfb7ee32f in main ()
```

I am considering completely changing how the updater works anyway.
