### ISSUE TITLE
Last open grid view can be closed from the grid view dock

### ISSUE THREAD

**Issue by cvuchener** [Dwarf-Therapist/Dwarf-Therapist#47]
Steps to reproduce:
 - Close all grid view tabs except one.
 - Last tab cannot be closed: "Cannot remove the last tab!".
 - From the Grid View dock, delete the grid view used in the last tab.
 - No grid view is visible and and neither is the menu for adding new tabs.
 - Dwarf Therapist crashes on exit:

```
#0  0x0000000000619223 in std::__atomic_base<int>::load (__m=std::memory_order_relaxed, this=0x614e656d65685464) at /usr/include/c++/7/bits/atomic_base.h:396
#1  QAtomicOps<int>::load<int> (_q_value=...) at /usr/include/qt5/QtCore/qatomic_cxx11.h:227
#2  0x000000000061901a in QBasicAtomicInteger<int>::load (this=0x614e656d65685464) at /usr/include/qt5/QtCore/qbasicatomic.h:102
#3  0x0000000000619cd6 in QtPrivate::RefCount::ref (this=0x614e656d65685464) at /usr/include/qt5/QtCore/qrefcount.h:55
#4  0x00000000007198f8 in QList<ViewColumnSet*>::QList (this=0x7fffffff1eb0, l=...) at /usr/include/qt5/QtCore/qlist.h:809
#5  0x00000000007197d9 in GridView::sets (this=0xfd0000) at /home/clement/projects/Dwarf-Therapist/src/gridview.h:70
#6  0x00000000007a0f80 in DwarfModel::clear_all (this=0x15be400, clr_pend=false) at /home/clement/projects/Dwarf-Therapist/src/dwarfmodel.cpp:77
#7  0x00000000007a0e3d in DwarfModel::~DwarfModel (this=0x15be400, __in_chrg=<optimized out>) at /home/clement/projects/Dwarf-Therapist/src/dwarfmodel.cpp:64
#8  0x00000000007a0ee8 in DwarfModel::~DwarfModel (this=0x15be400, __in_chrg=<optimized out>) at /home/clement/projects/Dwarf-Therapist/src/dwarfmodel.cpp:65
#9  0x00000000007773da in MainWindow::~MainWindow (this=0x15bd150, __in_chrg=<optimized out>) at /home/clement/projects/Dwarf-Therapist/src/mainwindow.cpp:322
#10 0x0000000000777506 in MainWindow::~MainWindow (this=0x15bd150, __in_chrg=<optimized out>) at /home/clement/projects/Dwarf-Therapist/src/mainwindow.cpp:328
#11 0x00000000006dd469 in DwarfTherapist::~DwarfTherapist (this=0x7fffffff1fa0, __in_chrg=<optimized out>) at /home/clement/projects/Dwarf-Therapist/src/dwarftherapist.cpp:120
#12 0x0000000000773d08 in main (argc=1, argv=0x7fffffff2118) at /home/clement/projects/Dwarf-Therapist/src/main.cpp:42
```

**Comment by RusTit** [comment]
I reproduced this bug, but I want to clarify a couple of things:
First you need to create, use, and then delete the custom grid view to reproduce bug.
I did not understand a little, what are the undesirable behavior?
I agree that there is a bug: the object is already deleted, but the pointer to it is still preserved.
Do you want that when deleting a custom grid view, if the tab is last, then it would not be closed? Can I even change the code so that custom tabs do not close at all when deleting the template?
P.S.
just describe the correct behavior of the app to solve this issue.
